### ISSUE TITLE
Utilitzar TWIG com a template engine per al WordPress

### ISSUE THREAD

**Issue by xavivars** [Softcatala/web-2015#1]
A l'hora de convertir la maqueta d'HTML a WordPress, ho podem fer directament en PHP o utilitzant algun *template engine* com **[Twig](http://twig.sensiolabs.org/)**. 

Un avantatge és que altres parts de la web, com per exemple la zona de recursos, ja utilitzen el mateix engine (encara que anomenat Jinja2, al tractar-se de la implementació de Python).

Existeixen extensions per al WordPress, com **[Timber](https://github.com/jarednova/timber)**, que permeten la implementació de temes utilitzant **Twig** de manera transparent.

**Comment by PauGNU** [comment]
Em sembla perfecte. +1 per twig

El dl. 22 de juny de 2015 13.10 Xavi Ivars <notifications@github.com> va
escriure:

**Comment by PauGNU** [comment]
Hi Softcatala/web-2015,

I&#39;d like to include you in my network to share updates and stay in touch.

- Pau

Confirm that you know Pau: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=ksEjVSnY&invitationId=6203268122112249857&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eivfj6d7k%7Exb








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ivfj6d7k-xb&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQG7TkzAFVKlaQAAAVhZvp5PDGh4ue3XNw_9op2gthWZkpbnRO8Cftrctx14GCHHphijAsBkTvKKHFCCS_B_j_QoiZpoZEuuUTLMQMWgc0KDwLWu4Qc3M2NOmg3SSRkI5q2uxD3bckOc5inFnEcbxEG4_scnfamXcL8-CUB94gX-qZ8e5Ta2zUc_d6BjLu4-PSg7&eid=0-ivfj6d7k-xb


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ivfj6d7k-xb&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by PauGNU** [comment]
Pau Iranzo would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=ksEjVSnY&invitationId=6203268122112249857&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-%7Ezwn8q%7Eivm5t5zo%7E73

View Pau Iranzo&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=ksEjVSnY&invitationId=6203268122112249857&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-%7Ezwn8q%7Eivm5t5zo%7E73





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-zwn8q-ivm5t5zo-73&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=-zwn8q-ivm5t5zo-73&loid=AQFuSzKVTBV42gAAAVhyaPfNkNpvOASRHUnF4OEj3tf7bsERdRkmrzr5DDXKHrTMLQ56Q6fxeOWccRS9TGwMuMMFwsRiP2EZ3R8t7HVythkBgdoQMAIJ5FcJ_srpLUk9fhbNVibtxWbLDVdqc-ZYRqkZXXLRIjdOc_HrUFpSG-vV-G-0p_4fYXrkaIUqfSi0LhEr

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-zwn8q-ivm5t5zo-73&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by PauGNU** [comment]
Hi ,

Pau Iranzo would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=ksEjVSnY&invitationId=6203268122112249857&trk=eml-second_guest_reminder_01-hero-120-accept_text&trkEmail=eml-second_guest_reminder_01-hero-120-accept_text-null-%7Ezwn8q%7Eiw1vb7vz%7Ep7

View Pau Iranzo&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=ksEjVSnY&invitationId=6203268122112249857&trk=eml-second_guest_reminder_01-hero-3-profile_text&trkEmail=eml-second_guest_reminder_01-hero-3-profile_text-null-%7Ezwn8q%7Eiw1vb7vz%7Ep7





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-zwn8q-iw1vb7vz-p7&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=122&m=unsub&ts=HTML&eid=-zwn8q-iw1vb7vz-p7&loid=AQEx1LLRtkqW1QAAAVirmEFwaZzWZ4Xa8iSy4VKsu3uYKNkGFuvXuoLsJ3w-iUa0xi4QEsCcaALixu29m3zZh47mTNpjqaScwDCgsJyK8jDAv454qgAAXDoYtIgH1FXHsQ1vhMxzrBGxQI5yqQLHvJOHhQAx8wZPFBFYlpkb_wKGs2CGpypx8vHeZGRC3xa_L8c90Kw-_w9k8p9hC4MICHBqcSWrPg

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-zwn8q-iw1vb7vz-p7&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
