### ISSUE TITLE
Es perd la selecció en la paginació de projectes

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#101]
Vaig a "Coneixeu Softcatalà" -> "En que treballem" -> "Projectes de traducció"

En la primera pàgina  "Coneixeu Softcatalà" m'apareix seleccionat dalt. Quan li dono a la segona pàgina em perd aquesta selecció del menú superior i em torna visualment a "Recursos i serveis"

**Comment by xavivars** [comment]
Arreglat
