### ISSUE TITLE
A la nova web els usuaris no poden donar-se d'alta de les novetats

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#103]
Actualment tenim 30.000 usuaris als quals informem quan publiquem una novetat a través d'un correu electrònic que s'envia a través de la llista novetats.

En l'antiga web hi havia l'opció "Subscripció a novetats" que permitia als usuaris subscriure's. En la nova web no tenim una opció.

Caldria pensar si volem continuar donant aquest servei (penso que sí) i amb quina visibilitat i pes a nou web.

**Comment by xavivars** [comment]
Call to action a les pàgines d'actualitat (notícies, esdeveniments...) que obra el formulari per a subscriure's
