### ISSUE TITLE
Redirecció del recull

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#104]
Aquesta URL https://www.softcatala.org/recull.html hauria d'apuntar a l'últim recurs que teníem. És un fitxer estàtic

**Comment by xavivars** [comment]
Potser alguna millor opció que tindre un fitxer estàtic (que escaparia del control de versions, etc)?

Possiblement és overkill, però una opció seria afegir-lo com a pàgina del WordPress

**Comment by xavivars** [comment]
> @jmontane: Escric la resposta demà, però crec que podem crear el projecte Recull de termes, ni que sigui per a arxivar-lo, i posar com a baixada la darrera versió

**Comment by jmontane** [comment]
## Què tenim?

- 1. Un projecte discontinuat (Recull) en favor d'un altre (Terminologia)
- 2. Una pàgina wiki de projecte no migrada [1]
- 3. Enllaços morts [2] (principal) i [3] (es fa servir?)
- 4. Una fitxa de programa per a Recull [4]
- 5. A [1] tenim un enllaç cap a [5] que redirigeix incorrectament cap a [6] (Recull de termes de Microsoft)

## Què podem fer?

- Sobre la fitxa de programa del Recull [4], cal decidir si la matenim o no. Jo la mantindria, també tenim la fitxa de la Guia d'estil.
- Si la mantenim, cal posar un avís que aquest document ha estat substituit pel projecte de Terminologia.
- Redirigir els URL [2], [3] i [5] cap a [4]
- Redirigir l'URL [1] cap a [7] (Terminologia). Alternativament, migrar el projecte de Recull al WP, arxivar-lo i redirigir [1] a l'URL del projecte Recull al WP.
 

[1] https://www.softcatala.org/wiki/Projectes/Recull_de_termes
[2] https://www.softcatala.org/recull.html
[3] https://www.softcatala.org/recull
[4] https://www.softcatala.org/programes/recull-de-termes-de-softcatala/
[5] https://www.softcatala.org/projectes/eines/recull/recull.htm
[6] https://www.softcatala.org/programes/recull-de-termes-de-microsoft/
[7] https://www.softcatala.org/projectes/recursos-linguistics-per-a-la-traducciomemoria-traduccio-de-softcatala/

**Comment by xavivars** [comment]
Gràcies Joan! La part que estic dubtós és què fer realment amb el recull "descarregable": abans recull.html era accessible per als cercadors, i de fet era normalment el primer resultat. Ara què faries, posaries això com a "baixada" a la fitxa del recull? I eixa baixada posar-la en algun ZIP/PDF?

**Comment by jmontane** [comment]
Tens raó,

he copiat el contingut del recull.htm a una pàgina de WP: https://www.softcatala.org/recull-termes-softcatala/

Ara només mancaria proporcionar un enllaç de baixada per a https://www.softcatala.org/programes/recull-de-termes-de-softcatala/, he obert un tiquet al projecte del Recull

**Comment by jmontane** [comment]
Ara tenim:

- Una pàgina al WP amb l'últim Recull publicat, versió 4.2: https://www.softcatala.org/recull-termes-softcatala/
- Un pàgina estàtica: https://www.softcatala.org/pub/softcatala/recull/recull.htm
- Un projecte abandonat, amb pàgina al wiki: https://www.softcatala.org/wiki/Projectes/Recull_de_termes
- Una fitxa de baixades que apunta a la pàgina de WP.

Manca:
- Redirigir l'URL antic https://www.softcatala.org/recull.html cap a la pàgina de WP.
- ¿L'URL https://www.softcatala.org/recull s'ha fet servir mai? en cas afirmatiu redirigir també cap a la pàgina de WP.

I amb això, em sembla que ja estaria tot.

**Comment by xavivars** [comment]
@jmontane: He redirigit tant recull.html com recull a la nova pàgina al WP. Amb el pròxim deployment que fem a producció haurien d'anar eixos redirects.

El que faria jo també és moure el projecte abandonat al wiki a l'estructura de projectes de WordPress, i esborrar la pàgina de la wiki (afegint també la redirecció corresponent). Què en penses?

**Comment by jordis** [comment]
Ara mateix l'enllaç cap al recull https://www.softcatala.org/projectes/eines/recull/recull.htm (que apareix en alguns llocs, com la Guia d'estil: https://www.softcatala.org/guia-estil-de-softcatala/terminologia/) redirigeix a la fitxa del recull de **Microsoft** (https://www.softcatala.org/programes/recull-de-termes-de-microsoft/)
Caldria que redirigís al Recull de Softcatalà [no sé exactament quin enllaç dels que proposàveu a dalt]

**Comment by xavivars** [comment]
He trobat enllaços per internet apuntant a /recull i a /guia.

Aquestos enllaços els hauriem de redirigir també on toque.

**Comment by xavivars** [comment]
Cal també fer neteja d'aquí: https://www.softcatala.org/wiki/Especial:Enlla%C3%A7os/Projectes/Recull_de_termes

**Comment by xavivars** [comment]
@jmontane: Al final he tingut temps per arreglar tot aquest desgavell. Pots pegar-li una ullada i dir-me si ho veus correcte?
