### ISSUE TITLE
problema amb wiki/Projectes/LanguageTool/PMF

### ISSUE THREAD

**Issue by jaumeortola** [Softcatala/web-2015#105]
L'adreça:
https://www.softcatala.org/wiki/Projectes/LanguageTool/PMF

reenvia a:
https://www.softcatala.org/projectes/languagetool/

En algun moment (abans de posar la web en producció) ha funcionat bé, però ara es repeteix el problema. 

La pàgina del projecte és a WordPress i la de PMF al wiki. No sé si hauria d'anar tot a WordPress.

**Comment by jaumeortola** [comment]
Sembla que passa amb totes les subpàgines de projectes. També en: 
https://www.softcatala.org/wiki/Projectes/LibreOffice/Manuals

**Comment by xavivars** [comment]
Ho tinc identificat. Intente arreglar-ho aquesta nit

--
Xavi Ivars
< http://xavi.ivars.me >
El dia 12 abr. 2016 8:09 p. m., "Jaume Ortolà" <notifications@github.com>
va escriure:

**Comment by xavivars** [comment]
Resolt
