### ISSUE TITLE
Problemes amb "Programari més baixat" a la portada

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#107]
En un Ipad mini 2 i un Android 6.0 es veu malament centrat
![rebost](https://cloud.githubusercontent.com/assets/309265/14412446/437317f6-ff63-11e5-9f97-b8c68e4aa14e.jpg)

**Comment by jaumeortola** [comment]
Relacionat amb això, en un mòbil no es veuen els noms dels programes.  El problema es reprodueix en un PC fent la finestra més petita. 
![captura de 2016-04-10 22 20 56](https://cloud.githubusercontent.com/assets/4289501/14412789/a013b34c-ff6a-11e5-8e07-a41d511607fe.png)

**Comment by jordimas** [comment]
Això que comenta en Jaume també ens succeïx a en @jmallach  i a mi

**Comment by leixet** [comment]
A mi també. Crec q les dues coses són el mateix problema.
