### ISSUE TITLE
Publicitat (mòbil + asíncron + zones)

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#109]
Cal continuar la feina amb publicitat:

La publicitat ha de carregar en mode asíncron
- [x] Traductor
- [x] Corrector
- [x] Diccionari de sinònims
- [x] Diccionari multilingüe
- [x] Capçalera
- [ ] Traductor mòbil

**Comment by xavivars** [comment]
Ja he posat la publicitat asíncrona a la barra lateral del traductor (tal i com ja està al corrector). 

Una vegada estiga funcionant, aquestos són els passos
1. El nostre webserver demana publicitat a Criteo
2. Criteo afegeix el seu javascript a la pàgina
3a.  Si Criteo pot mostrar publicitat, la mostra.
3b. Si Criteo no pot, fa una nova trucada al nostre adserver.
4. El nostre adserver demana publicitat a Google
5. Google mostra publicitat

Ara mateix, es mostra un quadre blanc, perquè Criteo (en el pas 3) es queda una mica atontat (sempre ho fa quan es creen noves zones). A mesura que va rebent peticions d'anuncis, comença a adonar-se que va de veres, i comença a aplicar 3a o 3b. Aniré monitoritzant demà com va la cosa.

Si tot va com toca, demà intentaré fer el mateix per als diccionaris, i dijous per a la part superior. Només faltarà la publicitat als serveis mòbils (per a això, cal pensar una miqueta).

**Comment by xavivars** [comment]
@jordimas la capçalera ja utilitza el bànner asíncron.

**Comment by jordimas** [comment]
Gràcies Xavi. Ho veig bé. Una prova que caldria fer és executar el Google Page Speed (https://developers.google.com/speed/pagespeed/insights/) contra web2015. Caldria llevar-li momentàniament la protecció a web2015 (el lloc ha de ser obert) com quan vam fer a casa de l'Anna un dia per provar-ho abans de pujar-ho.
