### ISSUE TITLE
Noms de projectes i persones en majúscules

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#111]
En la llista de projectes:

https://www.softcatala.org/en-que-treballem/traduccio-de-programari/

Usem majúscules i el noms com "LibreOffice" apareixen com "LIBREOFFICE"

Igual succeïx amb les persones:

https://www.softcatala.org/membres/

El meu nom és Jordi Mas no pas JORDI MAS.

Penso que hem de donar prioritat a la correctesa per davant de l'estil.

**Comment by jaumeortola** [comment]
Jo també he trobat estrany veure 28È PREMI... 
Escriure títols o noms en majúscula no és cap error, és un recurs legítim. "28È" potser sí que s'ha de considerar un error. 
Ccoses com LIBREOFFICE o 28È fan pensar que potser val més no usar les majúscules...

**Comment by xavivars** [comment]
Arreglat.
