### ISSUE TITLE
En fer els canvis a una fitxa de program es triga estona fins que l'usuari no registrat els veu

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#113]
En fer els canvis a una fitxa de program es triga estona fins que l'usuari no registrat els veu. Sembla que Redis no invalida bé la memòria cau

**Comment by xavivars** [comment]
Hem realitzat certs canvis a la configuració del Redis. Estaria bé que algú pugués comprovar-ho.

**Comment by xavivars** [comment]
Nous canvis fets. El problema era el següent
1. Tenim la web instal·lada darrere d'un nginx que fa de reverse proxy (main) i que enruta les peticions HTTPS al servidor intern, que les rep com a HTTP
2. WordPress està configurat per a "creure" que les peticions les rep per HTTPS i generar tots els URLs amb HTTPS
3. Nginx cercava a la memòria cau de Redis les peticions tal qual les rebia (HTTP) i, si no existien, les demanava al WordPress i després les guardava a la memòria cau **utilitzant com a clau la URL**
4. WordPress intentava esborrar les pàgines de la memòria cau de Redis amb la URL "final" de les pàgines (HTTPS), i no ho trobava.

S'ha resolt "forçant" a que Nginx busque i dese a Redis utilitzant sempre HTTPS com a part de la clau.

**Comment by xavivars** [comment]
En teoria està resolt. El tanque de moment
