### ISSUE TITLE
Desindexar el contingut de l'OpenThesaurus

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#116]
**Problema**

Ara les pàgines del diccionari de sinònims s'emeten per cada paraula (abans no). Això genera una pàgina per terme competeix amb el contingut de OpenTheasurus. Veure https://openthesaurus.softcatala.org/synonyme/taula - i https://www.softcatala.org/diccionari-de-sinonims/paraula/taula/

Google té indexades de dues URL.

Cal tenir en compte a més els enllaços externs que ja té l' OpenTheasurus, com ara els de Viccionari https://ca.wiktionary.org/wiki/c%C3%B3rrer que poden tenir bastant pes.

**Solució**

Proposta:
- Cal posar-hi no index a les pàgines d'OpenThesaurus (perquè surtin de l'índex)  i afegir-ho al robots.txt perquè google no les baixi
- Actualitzar amb un bot els enllaços de Viccionari (en @jaumeortola  podria ajudar)

**Comment by xavivars** [comment]
@jordimas: això és el que vas resoldre tu fa uns mesos, veritat? L'OT ja redirigeix a SC per a consultes de pàgines individuals.

**Comment by jordimas** [comment]
Correcte, ja ho vaig solucionar.
