### ISSUE TITLE
Títols llargs no visibles en Aplicacions i programes

### ISSUE THREAD

**Issue by jaumeortola** [Softcatala/web-2015#117]
En la secció d'Aplicacions i programes/Llengua en molts casos no hi ha prou text visible per a saber de quin programa es tracta. Per exemple, en la imatge les 5 versions de LT no es distingeixen. Quan el nom del programa és només una paraula, no hi ha problema. Però quan el nom és més llarg, s'ha de fer algun ajust. O permetre que es vegi més text. O escurçar els noms dels programes (ex. LanguageTool per a Chrome, LanguageTool per a LibreOffice).
![captura de 2016-04-10 22 46 41](https://cloud.githubusercontent.com/assets/4289501/14413006/45c16980-ff6e-11e5-82ac-1b8f7f651fc3.png)

**Comment by PauGNU** [comment]
Ara mateix es retallen els títols per a que no mostren més de x paraules (no sé si són 5 o 6). El problema és que quan el títol del programa és més llarg, llavors el disseny es desquadra perquè les caixes tenen diferents mides (seria l'esperat). Llavors, o fem les caixes més grans (això crec que faria més lleig el disseny), o retallem els títols dels programes (o continuem com estem fins ara).

**Comment by jaumeortola** [comment]
La prioritat crec que ha de ser resoldre la qüestió pràctica: hi ha 4 o 5 versions d'un programa i l'usuari no sap quina és cada una. 
Amb la mida de lletra que hi ha ara jo crec que ja cabrien pràcticament els títols més llargs. (Valdria més tallar per nombre de caràcters que per nombre de paraules. S'aprofitaria més l'espai). Jo faria els ajusts que calgueren perquè és vera tot (lletra més menuda, icona un pèl més menuda, etc.). 
Quant al disseny, el que donaria un aspecte més "endreçat" és que els noms començaren tots a una altura fixa, i que la icona quedara centrada en l'espai de dalt. 
Demanem més opinions?

**Comment by PauGNU** [comment]
@jaumeortola, @jordimas 

Vam fer el canvi fa un temps per tindre els títols dels programes en 'normalcase' en lloc de majúscules. Això ens dóna marge per retallar en 9 paraules en lloc de 5 com està ara. Tot i així, hi ha alguns programes que tenen un títol de més de 9 paraules, per exemple: «Corrector gramatical en català LanguageTool per al LibreOffice – Apache OpenOffice». Des del meu punt de vista:

- Canviem a 9 paraules
- Els programes de més de 9 paraules tindran el títol retallat

Si no retallem el títol, ens trobarem amb un problema de disseny, ja que tindrem requadres que seran més alts que altres i això desquadra tot amb la maquetació actual. Tot i així, encara que s'arreglara això, posar mides de caixa de cada programa més gran del que hi ha ara seria lleig.

Faré el canvi a 9 paraules en qualsevol cas!

**Comment by jaumeortola** [comment]
Doncs bé. Fem això que proposes. Fem-ho prompte perquè és molt incòmode no veure els noms dels programes.

**Comment by xavivars** [comment]
@jaumeortola tu consideres que açò està resolt?

Jo diria que si, però voldria que digueres què en penses.

https://www.softcatala.org/programes/cat/llengua/

**Comment by jaumeortola** [comment]
Sí, ara la majoria es distingeixen bé. Donem-ho per resolt.
