### ISSUE TITLE
https://www.softcatala.org/catalanitzador/stats/ no mostra la web d'estadístiques

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#118]
https://www.softcatala.org/catalanitzador/stats/ no mostra la web d'estadístiques. És important ja que l'usem per fer un seguiment dels usuaris i incidències

Cal assegurar-se que parser.php funciona bé

Recordeu que tenim dos entorns tant del parser com d'estadístiques:
https://www.softcatala.org/dev-catalanitzador/parser.php
https://www.softcatala.org/catalanitzador/parser.php

**Comment by xavivars** [comment]
Ja està habilitat. Tambe https://www.softcatala.org/catalanitzador/response.php (i l'equivalent en DEV) que ens dóna el número de catalanitzacions fetes.

**Comment by jordimas** [comment]
Ei Xavi

Els estils no carreguen: https://www.softcatala.org/catalanitzador/stats/ i es veu horrible. No troba https://www.softcatala.org/catalanitzador/stats/style.css (entre d'altres coses)

**Comment by xavivars** [comment]
Fet.

**Comment by jordimas** [comment]
Ara carrega els estils però no mostra cap gràfic

**Comment by PauGNU** [comment]
Hola Jordi, 

He canviat les referències js a dintre del directori d'estadístiques per resoldre el problema. Està tot bé ara?

**Comment by jordimas** [comment]
Ja es veu bé. Cal solucionar el mateix problema a: https://www.softcatala.org/dev-catalanitzador/stats/

**Comment by PauGNU** [comment]
Corregit :).
