### ISSUE TITLE
No funcionen els entorns de dev i preprod de recursos

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#120]
Les adreces https://www.softcatala.org/recursos-dev/ i https://www.softcatala.org/recursos-preprod/ jo responen. Segurament em perdut l'enrutament del nginx. 

Recursos fa servir [tests d'integració ](https://github.com/Softcatala/translation-memory-tools/tree/master/integration-tests)(que ataquen l'API) per desplegar automàticament a l'entorn si passen, com els entorns no es veuen no puc desplegar versions.

A la pàgina de "recursos" d'intern tenim descrit el mapping de ports

**Comment by xavivars** [comment]
@jordimas: aprofitant que ara tenim més d'un entorn per a la web, com vols que connecte els diferents entorns?

* [ ] recursos-prod
 * www.softcatala.org/recursos/ :white_check_mark: 
* [ ] recursos-preprod
 * web2015.softcatala.org/recursos/  ?
 * www.softcatala.org/recursos-preprod/ ?
* [ ] recursos-dev
 * web2015.softcatala.org/recursos/  ?
 * www.softcatala.org/recursos-dev/ ?

**Comment by jordimas** [comment]
Hola Xavi,

Té sentit que quan vas a web2015.softcatala.org/recursos/ et dirigeixi a www.softcatala.org/recursos-dev/.

A part d'això necessito visibilitat de www.softcatala.org/recursos-preprod/ i www.softcatala.org/recursos-dev/ com teníem abans.

Gràcies!

Jordi,

**Comment by xavivars** [comment]
Oks.

**Comment by xavivars** [comment]
Ja hauria d'estar funcionant correctament. Pots comprovar-ho i tancar el ticket?
