### ISSUE TITLE
robots.txt

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#121]
A [robots.txt](https://www.softcatala.org/robots.txt) actual li manquen moltes coses: exclusió de mediaWiki, dels entorns dev i preprod de recursos, el temps de crawling, etc

Hauríem de posar-lo aviat perquè els crawlers de Google i altres cercadors han de revisitar tot el lloc i això els ajudarà

**Comment by PauGNU** [comment]
Ja ho tenim a prod. Pots comprovar-ho?

**Comment by PauGNU** [comment]
(caldrà fer canvis)

**Comment by jordimas** [comment]
Hola Pau,

Al robots.txt hi ha fitxers especifics com:

https://www.softcatala.org/CHANGELOG.txt

que no existeixen. Llavors no haurien de ser-hi al robots.txt

Per la resta ho veig bé.

Jordi,

**Comment by xavivars** [comment]
He d'afegir encara certes coses relatives al WP. M'assigne el ticket i ho continue jo demà.

**Comment by xavivars** [comment]
Eliminat la major part del robots. També he baixat el temps de crawl delay de 10 a 2
