### ISSUE TITLE
Imatges massa grans a les pàgines distribuidores

### ISSUE THREAD

**Issue by xavivars** [Softcatala/web-2015#124]
A les pàgines distribuidores (p. ex. [Espai de col·laboradors](https://www.softcatala.org/espai-de-col·llaboradors/) hi ha incloses imatges **ENORMES** (+3MB).

Cal reduir-les.

**Comment by PauGNU** [comment]
Hola,

Ho estic mirant. He afegit la funció resize, però el valor que retorna no és bo. Vaig a vore perquè l'sc-normalize-uploaddir no funciona bé (retorna valors com: 
/wp/wp-content/var/www/softcatala.local/htdocs/uploads/2016/04/05ab01f3cac7a55d942514926f9c1ba4.png
