### ISSUE TITLE
Flux de "col·laboreu en el projecte"

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#127]
Actualment quan un usuari demana "col·laboreu en el projecte" Si la llista no està definida, s'envia la informació a web@softcatala.org <mailto:web@softcatala.org>. 

Té més sentit seguir aquesta lògica:

* Si hi ha llista definida subscriure'l
** Atenció: cal deixar més clar que vol dir susbcriure's a una llista, que s'ha de presentar a la mateixa, etc
* Responsable de projecte
* Finalment web@softcatala.org

**Comment by xavivars** [comment]
Pensant-ho millor, potser val la pena enviar SEMPRE un correu electrònic al responsable del projecte, tant si es subscriu a la llista com si no, per si eixa persona no es presenta, i el responsable vol, pot contactar amb ell...

Què en penses, @jordimas ?
