### ISSUE TITLE
Detalls de membre: La foto no respecta la relació d'aspecte en versió mòbil

### ISSUE THREAD

**Issue by jordis** [Softcatala/web-2015#128]
Al mòbil les fotos de membres surten aixafades en mode vertical. En apaïsat surten bé.
![photo10980346341468150](https://cloud.githubusercontent.com/assets/2217732/14460049/aa799b4c-00bb-11e6-84f6-fd54d6758b1c.jpg)
També es pot veure el problema a la versió escriptori si es va jugant amb la mida de la finestra.
Les fotos haurien de mantenir la relació d'aspecte.

**Comment by xavivars** [comment]
Arreglat
