### ISSUE TITLE
El menú principal no funciona a Terminologia

### ISSUE THREAD

**Issue by jmontane** [Softcatala/web-2015#129]
Si estàs a Terminologia [1] no funciona el selector del menú principal: Recursos i Serveis| Coneixeu Softcatalà | Col·laboreu amb l'associació

[1] https://www.softcatala.org/recursos/terminologia.html

**Comment by xavivars** [comment]
@jordimas: Cal actualitzar els SSI de recursos, no contenen els canvis que vam fer des de dissabte, tant a nivell d'html com d'estils

**Comment by jordimas** [comment]
No és una qüestió de la versió de SSI. El que succeïx és que no estàvem incloent-hi JQuery en alguns casos i en altres l'estàvem però no la versió adequada. Demà estarà on-line solucionat.

**Comment by xavivars** [comment]
:+1:

**Comment by xavivars** [comment]
A recursos-dev ja està resolt

**Comment by jordimas** [comment]
Ja està resolt a producció.
