### ISSUE TITLE
Spam i esborrat de contingut real a la Wiki

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#133]
Ens esta entrant spam a la Wiki:

https://www.softcatala.org/wiki/Especial:Canvis_recents

A més estan esborrant contingut real per emplaçar-lo per spam

Crec recordar que en @toniher va fer una modificació per preguntar quina era una comarca. Caldria implementar una protecció semblant a la que teniem abans

**Comment by PauGNU** [comment]
Hola,

Per ara: he desactivat el registre i l'edició per part de persones anònimes

**Comment by PauGNU** [comment]
Hola,

He fet un esborrat manual d'usuaris i pàgines modificades. Hauré de comprovar el tema d'activar la protecció anti-spam.
