### ISSUE TITLE
Guia d'estil: s'han perdut els colors (verd/vermell/...) en les taules

### ISSUE THREAD

**Issue by jordis** [Softcatala/web-2015#139]
Abans les taules de correcte/incorrecte estaven marcades amb colors vermell/verd.
Ara surten totes en gris.
Exemple: https://www.softcatala.org/guia-estil-de-softcatala/convencions-de-format/
![screenshot - 16_04_2016 15_33_44](https://cloud.githubusercontent.com/assets/2217732/14581261/a6778128-03e8-11e6-9c0f-1d87347dcb7f.png)

**Comment by xavivars** [comment]
Gairebé no es veu...
