### ISSUE TITLE
Correcció: terminològia -> terminologia 

### ISSUE THREAD

**Issue by jordis** [Softcatala/web-2015#142]
Al títol de la pàgina: https://www.softcatala.org/recursos/terminologia.html
Caldria canviar: terminològia -> terminologia 
Sembla que és una pàgina estàtica que no puc editar

**Comment by PauGNU** [comment]
@jordimas te n'encarregues tu?

**Comment by jordimas** [comment]
En @jaumeortola  ho ha solucionat:

https://github.com/Softcatala/translation-memory-tools/commit/70d43b61028c5bc0939c3018b30756689aa69e14

Estarà a producció en les properes 48 hores. Si no és així re-obrir el issue.
