### ISSUE TITLE
Índex de paraules pel diccionari de sinònims

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#143]
Actualment Google no té cap paraula del diccionari de sinònims a l'índex:

site:https://www.softcatala.org/diccionari-de-sinonims/

Això es degut a que no té enllaços interns a les paraules i no les troba,

La solució seria fer un índex de paraules tal com tenim al diccionari multilingüe. 

Un cop #116 estigui implementat es pot pujar aquest canvi per minimitzar el contingut duplicat

**Comment by PauGNU** [comment]
Hola @jmontane , saps si existeix una crida api de l'openthesaurus per recuperar totes les paraules que comencen per una lletra específica?

**Comment by jmontane** [comment]
Cal actualitzar el codi de l'OT-ca a l'última versió d'upstream i podrem fer-ho.

**Comment by xavivars** [comment]
Increïble: encara sense enllaços, i Google ja té indexades moltes paraules...

**Comment by jmontane** [comment]
Tinc pendent de posar la versió d'upstream de l'OT. Això permetria indexar totes les paraules fàcilment. Confio poder-ho fer abans de finals d'agost.

**Comment by xavivars** [comment]
@jmontane sé que serà complicat, però per demanar que no quede :)

Este estiu tindrem sort?

**Comment by jordimas** [comment]
Tanco ja ho que tenim nou sistema de sinònims
