### ISSUE TITLE
El bóto "mostra els canvis" de la Wiki no funciona

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#144]
Quan editem una pàgina de la Wiki l'opció "mostra els canvis", que mostra una diff amb els canvis, es mostra en blanc en comptes de mostrar els canvis. Si no vas molt en compte, a més perds tots els canvis, ja que quan entres en aquesta pantalla no surt cap botó. Només una pàgina en blanc.

**Comment by xavivars** [comment]
He trobat el motiu: tota la secció està amagada sota un "display:none".

El que no entenc és perquè @PauGNU va posar això: https://github.com/Softcatala/mw-softcatala/blob/master/SoftcatalaTemplate.php#L87

@PauGNU, podríes revisar-ho quan tingues un moment?

**Comment by xavivars** [comment]
Arreglat
