### ISSUE TITLE
Mostrar els projectes en ordre alfabètic a la pàgina de projectes

### ISSUE THREAD

**Issue by jmontane** [Softcatala/web-2015#145]
Ara mateix els projectes a https://www.softcatala.org/projectes es mostren segons l'id intern. Caldria mostrar-los ordenats alfababèticament pel nom del projecte.

**Comment by xavivars** [comment]
Sembla que ja està resolt... 
https://github.com/Softcatala/wp-softcatala/commit/40baa3cf
