### ISSUE TITLE
Alguns cop el giny de baixades a portada no mostra contingut

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#147]
Alguns cops el giny de baixades a portada no mostra contingut. L'HTML ve buit. M'ha passat més d'un cop. Avui entre 7.00 i 7.30. Potser té que veure a l'hora que es genera?

![rebost2](https://cloud.githubusercontent.com/assets/309265/15096223/23bc7b1c-14f0-11e6-959a-96e013534c63.jpg)
![rebost](https://cloud.githubusercontent.com/assets/309265/15096222/23ba53a0-14f0-11e6-991a-db15e4b90143.jpg)

**Comment by PauGNU** [comment]
De vegades falla i no retorna res, però en 30 minuts se soluciona. Ara ja
funciona.

Caldrà gestionar l'error quan passa.

El dg., 8 maig 2016 7.40, Jordi Mas <notifications@github.com> va escriure:

**Comment by jordimas** [comment]
Sabem perquè alguns cops falla i no retorna res? Està bé gestionar millor l'error però també caldria solucionar el problema d'arrel.

**Comment by xavivars** [comment]
Com a mínim, si no som capaços de "solucionar" el problema d'arrel, el que hauríem de fer és mantenir el giny amb les dades antigues, fins que es puguen generar les noves.

**Comment by xavivars** [comment]
Es resoldrà amb #154

**Comment by PauGNU** [comment]
Hi Softcatala/web-2015,

I&#39;d like to include you in my network to share updates and stay in touch.

- Pau

Confirm that you know Pau: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=02wVnTu4&invitationId=6203268122275823616&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eivfj6gry%7Eou








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ivfj6gry-ou&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHEDbqaFoJ8BQAAAVhZvqA2gaHyPZYG5OpIXVtXc8I0xS89S9IWZz9a4vHBvS_TAjTOOVa-9tqeHjSoEFKMnUmbX-zWcubOFDmlk3ENULQCg44L1wYWsRVQFLpyuTj8cSTkP3eGo42mdQANS1lWKN7PZ5LeAx5zhcQfmOZsALPjOcpXa_XenQJ_yRCcyMAi8mSK&eid=0-ivfj6gry-ou


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ivfj6gry-ou&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by PauGNU** [comment]
Pau Iranzo would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=02wVnTu4&invitationId=6203268122275823616&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-2tv7k2%7Eivm5unk6%7Eye

View Pau Iranzo&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=02wVnTu4&invitationId=6203268122275823616&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-2tv7k2%7Eivm5unk6%7Eye





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=2tv7k2-ivm5unk6-ye&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=2tv7k2-ivm5unk6-ye&loid=AQFV_Pmje6IdngAAAVhybKLyCKOgKjqm5p67Z7Xvlye8W_GntnhbrURBEV1SwMSbt_L1pWkUnvKNqPqBOMnsvA-un9Hi05E_5XiLmRLyzccYu3q22nIAKEkXzhcxdDOHjOG9zL3_HKgmxJn66Gbs2UKgw_C0W0xb6VKuDxOIy0rxf7PM75L59i73hi2cawspKg0u

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=2tv7k2-ivm5unk6-ye&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by PauGNU** [comment]
Hi ,

Pau Iranzo would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=02wVnTu4&invitationId=6203268122275823616&trk=eml-second_guest_reminder_01-hero-120-accept_text&trkEmail=eml-second_guest_reminder_01-hero-120-accept_text-null-2tv7k2%7Eiw1vbe3o%7Exv

View Pau Iranzo&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=02wVnTu4&invitationId=6203268122275823616&trk=eml-second_guest_reminder_01-hero-3-profile_text&trkEmail=eml-second_guest_reminder_01-hero-3-profile_text-null-2tv7k2%7Eiw1vbe3o%7Exv





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=2tv7k2-iw1vbe3o-xv&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=122&m=unsub&ts=HTML&eid=2tv7k2-iw1vbe3o-xv&loid=AQEK2r-8M1WXygAAAVirmmoBvPC5mxvieOI305wNO9avXNT_94Cp0s8SceAfmfBEE-XWiKiixUueXHLtEgulUpBd0zsvHL6ksYH2aVSxWzsaJdH0ASRH9kkY_3wkqaSgYcufGASsys7R3MrfNgEP5w7J7a3ZUGPQwkyoSCW0RiTHHlonqBmeg_uLcfk0qEWfgHPFPhQp3e3MAo2rKZEWKMvVlsdqTA

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=2tv7k2-iw1vbe3o-xv&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
