### ISSUE TITLE
Avís de seguretat a algunes pàgines de membres

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#148]
A pàgines com:

https://www.softcatala.org/membres/jmas/
https://www.softcatala.org/membres/xavivars/
https://www.softcatala.org/membres/pau/

En Firefox es mostra el candau en color groc indicant que la pàgina barreja http i https

La consola mostra aquest error:

"S'està carregant contingut mixt visual (insegur) «http://gravatar.com/avatar/bfdf92dc67083ee25efc6f772814e70f?size=270» en una pàgina segura"

**Comment by jmallach** [comment]
gravatar sembla servir contingut per https sense problemes...
