### ISSUE TITLE
Cal actualitzar les capçaleres dels fòrums

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#149]
Les capçaleres dels fòrum són antigues:

- Hi ha centenars d'enllaços trencats perquè encara tenen enllaços com https://www.softcatala.org/recursos-per-a-traductors que són 404 (això es va solucionar). Aquest error es replica a cada pàgina
- Tenen els textos en minúscules i altres millores que s'han anat fent sobre els menús

**Comment by PauGNU** [comment]
Hola,

Està fet. Només calia fer un git pull al servidor del fòrum. Caldrà automatitzar això al fabric (també està pendent de fer-ho amb mediawiki).
