### ISSUE TITLE
Exportar metainformació de les fitxes del directori del programa per tenir més detalls al SERP

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#150]
Exportar metainformació de les fitxes del directori del programa perquè Google mostri més detalls que l'usuari fa un cerca, és a dir, tenir més detalls al SERP (https://en.wikipedia.org/wiki/Search_engine_results_page). La majoria de directoris de programes fa temps que ho fan.

![serp](https://cloud.githubusercontent.com/assets/309265/15136364/4429ec80-1681-11e6-8a2c-f7a6c53c0de7.jpg)

Veure: https://schema.org/AggregateRating

Exemples:
* http://gbrainy.softonic.com/
* http://download.cnet.com/Gbrainy/3000-2111_4-10824752.html

**Comment by xavivars** [comment]
Issue ja obert al repositori del tema: https://github.com/Softcatala/wp-softcatala/issues/101

**Comment by pereorga** [comment]
Com comentàvem, això també podria permetre habilitar la cerca interna dels diccionaris de sinònims (i multilingüe, o el futur anglès-català) des de Google, com fa Merriam Webster, per exemple:

 https://www.google.com/search?q=merriam+webster

![merriam](https://user-images.githubusercontent.com/919779/166153414-d6932c11-0929-456e-a0cb-e6ee9bafc5e5.png)


Més informació:
https://schema.org/SearchAction
https://developers.google.com/search/docs/advanced/structured-data/sitelinks-searchbox
