### ISSUE TITLE
Més claretat cerca d'esdeveniments 

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#151]
Si vaig a https://www.softcatala.org/esdeveniments/ i cerco Pompeu:

https://www.softcatala.org/esdeveniments/?cerca=pompeu

No em torna cap resultat però me'l mostra a l'entrar.

Entenc que això succeïx perquè és un esdeveniment passat. Correcte? No és clar que et mostri esdeveniments en entrar en la pàgina que després la cerca no trobi.

Potser cal mostrar diferent (un altre color) els esdeveniments passats o explicar que només cerca els que encara no han succeït

**Comment by xavivars** [comment]
Segurament és un error que no isca. Haurem de fer que isquen tots els esdeveniments, i marcar d'alguna manera els que ja han passat.

**Comment by jordimas** [comment]
Tanco això ja que vam llevar la funcionalitat
