### ISSUE TITLE
La cerca no dóna cap resultat si inclou caràcters tipogràfics

### ISSUE THREAD

**Issue by jordis** [Softcatala/web-2015#152]
A la cerca global,
cerco: `d’interfície`  [amb apòstrof tipogràfic] --> 0 resultats
cerco: `d'interfície`  [amb apòstrof no tipogràfic] --> uns quants resultats
Passa el mateix amb les cometes:
`“hola”` (cap resultat) vs. `"hola"` (uns quants resultats)

Es podrien normalitzar els caràcters tipogràfics per tal que en la cerca els detecti com a no tipogràfics?

**Comment by xavivars** [comment]
Probablement, la única opció és filtrar el SQL de la cerca ací

https://core.trac.wordpress.org/browser/trunk/src/wp-includes/query.php#L2812
