### ISSUE TITLE
Enllaç incorrecte en el fòrum

### ISSUE THREAD

**Issue by cubells** [Softcatala/web-2015#153]
En fer clic a l'índex de lletres de membres del fòrum, dóna un error l'nginx, segurament per l'url.
Prova: feu clic a qualsevol lletra de l'índex.

![captura de 2016-06-01 22 40 05](https://cloud.githubusercontent.com/assets/4386443/15725041/33966f80-284a-11e6-9719-c884466c26d5.png)

**Comment by xavivars** [comment]
El problema sembla que és a la pròpia generació dels enllaços, a https://github.com/Softcatala/sc-phpbb/blob/master/template/memberlist_body.html#L37

@PauGNU: t'ho pots mirar tú?

**Comment by xavivars** [comment]
Fixed in https://github.com/Softcatala/sc-phpbb/commit/058806ced6290b62450fbec679ca2484efa16296
