### ISSUE TITLE
Si el programa té un nom llarg no es veu complet en els llistats

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#158]
Si el programa té un nom llarg no es veu complet en els llistats. Veure l'exemple de Language Tool o el corrector.

![rebost](https://cloud.githubusercontent.com/assets/309265/16525517/13ee1dd4-3fad-11e6-81c4-fe4ddfe32c3f.jpg)

**Comment by jaumeortola** [comment]
Això ja estava dit: https://github.com/Softcatala/web-2015/issues/117, i crec que és important arreglar-ho.

**Comment by PauGNU** [comment]
#duplicat
