### ISSUE TITLE
Les URL del paginador de notícies fan 301

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#159]
A: https://www.softcatala.org/noticies/

Les URL dels botons per canviar de pàgina com ara:

https://www.softcatala.org/noticies/page/2

fa sempre 301 a:

https://www.softcatala.org/noticies/page/2/

A https://www.softcatala.org/programes/ tenim el mateix problema. Potser generalitzat.

**Comment by PauGNU** [comment]
Hola,

És una miqueta raro. El codi de generació el fem servir correctament. Al 2013 alguns usuaris es van queixar d'això amb el Timber (https://github.com/timber/timber/issues/58). No vull afegir el '/' directament. A veure si trobe alguna altra raó...

**Comment by xavivars** [comment]
Ja ho he trobat (i obert el bug upstream)
 https://github.com/timber/timber/issues/1109

**Comment by xavivars** [comment]
Ja hem solucionat el problema (era amb el Timber, upstream).

Amb la propera versió de l'extensió estarà solucionat.

**Comment by jordimas** [comment]
Gràcies Xavi, molt bona feina!
