### ISSUE TITLE
LibreOffice: baixades

### ISSUE THREAD

**Issue by xavivars** [Softcatala/web-2015#161]
Ambdós baixades (32 i 64 bits) apareixen com a 32 bits.

**Comment by xavivars** [comment]
https://github.com/Softcatala/web-2015/blob/master/scripts/sc_cron.php#L214: Busca x86-64 al nom del fitxer, però el fitxer només té x64.

**Comment by jmontane** [comment]
L'URL de baixada del paquet de llengua d'OSX i Linux no s'actualitza correctament. Ara mateix:

El fitxer amb les dades (https://gent.softcatala.org/jmontane/libo/latest_files.txt) indica l'URL de baixada de la versió 5.2.1
La fitxa (https://www.softcatala.org/programes/paquet-catala-valencia-per-al-libreoffice/) apunta a la versió 5.1.1
