### ISSUE TITLE
Suprimir el Javascript bloquejant de la pàgina

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#166]
Actualment Google Page Speed https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fwww.softcatala.org&tab=mobile ens dóna una puntuació bastant baixa 60 sobre 100.

El problema principal són els JS:

Suprimir el JavaScript que bloqueja la renderització:

```
https://www.softcatala.org/themes/wp-softcatala/static/js/ads.js
https://ad.softcatala.org/…=UTF-8&loc=https%3A//www.softcatala.org/
https://ad.softcatala.org/www/delivery/fl.js
https://cas.criteo.com/…c=https%3A//www.softcatala.org/&mmm_fo=1
https://ad.softcatala.org/…c=https%3A//www.softcatala.org/&mmm_fo=1
```

Ús de versions asíncrones dels scripts següents:

```
https://pagead2.googlesyndication.com/pagead/show_ads.js
https://pagead2.googlesyndication.com/pagead/show_ads.js
```

El millor seria carregar-los amb async si és possible.

Veure també: https://search.google.com/search-console/mobile-friendly?utm_source=psi&utm_medium=link&utm_campaign=psi-ux-banner&hl=ca-ES

**Comment by xavivars** [comment]
Depén de https://github.com/Softcatala/web-2015/issues/109

**Comment by xavivars** [comment]
@jordimas he fet els canvis relacionats amb els JS, i ha pujat a 86/71.

Ara el que demana és llevar els CSS bloquejants però, de moment, no em centraria totalment en això.
