### ISSUE TITLE
Detecció de Windows Phone a la fitxa del Traductor

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#168]
Quan des d'un Windows entres a aquesta fitxa:

https://www.softcatala.org/programes/traductor-softcatala/

Pre-selecciona la baixada de Windows quan realment no tens un dispositiu perquè s'instal·la. Sembla que estem confonent Windows Desktop amb Windows Phone en la detecció de plataforma.

El user agent del navegador on succeïx: 

Mozilla/5.0 (Windows NT 6.0; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by xavivars** [comment]
Segons tu, quina baixada s'hauria de seleccionar? Perquè sempre se'n selecciona alguna...

**Comment by jordimas** [comment]
Pensava que hi havia la possibilitat que no és seleccionés cap, com fa Google Play.

**Comment by xavivars** [comment]
Sempre donem la opció de descarregar alguna cosa: el cas del traductor, on només hi ha aplicacions mòbils, és únic en tot el rebost
