### ISSUE TITLE
La wiki no permet pujar imatges

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#171]
Dos problemes:
1. L'opció no està disponible en el menú lateral d'edició
2. Si s'accedeix la URL directament (https://www.softcatala.org/wiki/Especial:Carrega) diu "S'ha inhabilitat la càrrega"

**Comment by PauGNU** [comment]
Hola Jordi,

He habilitat les pujades al LocalSettings.php. Ara hauries de poder utilizar l'url de càrrega. Estic mirant el tema de que aparega al menú.

**Comment by PauGNU** [comment]
Hola,

He modificat la barra lateral per incloure un bloc d'enllaços que no havia inclòs inicialment. Allà s'hi troba l'opció de càrrega de fitxers :)
