### ISSUE TITLE
La cerca superior de la capcerlera no va a les web no WP

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#185]
La cerca superior (la lupa al costat de Necessiteu Ajuda) de la capçalera no funciona a les web no WP, per exemple:
- [x] Fòrums
- [x] MediaWiki
- [ ] Recursos

**Comment by xavivars** [comment]
- [ ] Fòrums resolt. Només calia tindre en compte que els JS es poden carregar abans que l'HTML.

**Comment by xavivars** [comment]
- [ ] MediaWiki resolt: el JS del SSI estava desactualitzat.

**Comment by xavivars** [comment]
- [ ] Recursos ja està també. He hagut de fer alguns canvis als HTML, ja que estaven referenciant els fitxers de manera incorrecta. En la propera regeneració de la web de recursos, hauria de començar a funcionar,.
