### ISSUE TITLE
Mostra la data amb el format correcte.

### ISSUE THREAD

**Issue by Ecron** [Softcatala/web-2015#187]
A les notícies, quan es mostra la data de publicació baix de les etiquetes, no es mostra amb el format correcte, només amb el dia, el nom del mes i l'any (tipus `26 juny 2017` en compte de `26 de juny de 2017`).

![captura de pantalla de 2017-06-27 13-49-20](https://user-images.githubusercontent.com/488803/27586791-0514641a-5b42-11e7-91de-3d769bf6233d.png)

Hi ha alguna forma de solucionar-ho?

**Comment by xavivars** [comment]
@Ecron arreglat
