### ISSUE TITLE
No arrosseguem la plataforma identificada

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#190]
Des d'un mòbil amb Android, a l’entrar a la pàgina principal podem veure el programari més baixat. Llavors, fem clic a “Més programari”. Obtenim un llistat complet de programari i no s arrosega la detecció de plataforma inicial. Com a resultat, em surten tots els resultats (que no són rellevants pel meu dispositiu) sense filtrar per plataforma. He de tornar a seleccionar “Android”.

Solució: que la detecció de plataforma que usem pel top 5 del rebost s’arrosegui amb una galeta a tot arreu i que només es sobre-escrigui si l’usuari selecciona un altre plataforma

**Comment by xavivars** [comment]
@jordimas: Hi veig un problema: no donem accés mai a la llista de tots els programes des del giny de programes més baixats?

**Comment by leixet** [comment]
¿Es podria deixar seleccionat al desplegable de cerca la opció del sistema operatiu de l'usuari segons informi la cookie i potser implementar un botó al costat que netegi els camps de cerca (perquè es vegi clar q només s'està visualitzant els resultats filtrats pel sistema operatiu detectat)?

**Comment by jordimas** [comment]
Hem quedat amb en Xavi de parlar-ne a la trobada presencial de Setembre.
