### ISSUE TITLE
Els resultats de la cerca no són rellevants

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#191]
Entro a https://www.softcatala.org/programes/. Cerco “Firefox” pel tal de trobar el Firefox per a mòbil. El Firefox apareix com a 6 resultat.

Solució: L'algortime de rellevància de resultats de cerca hauria de donar molt de pes al títol, ja que és normal que la gent cerqui aplicacions pel títol

**Comment by xavivars** [comment]
Ja hi ha una primera aproximació a això. He canviat per a que la cerca noḿes tinga en compte el títol. El problema és que la cerca del WordPress no funciona bé del tot, i quan es cerca només una paraula, els pesos són molt dolents. Crec que limitant la cerca al títol, es millora considerablement la rellevància dels resultats.
