### ISSUE TITLE
Es mostren categories al selector sense contingut per la plataforma

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#193]
Cas d'ús: com a usuari vull entendre quins programes hi ha disponibles en IOS

Si anem al selector de programes i seleccionem "IOS":

https://www.softcatala.org/programes/so/ios/

Veurem que hi ha categories que podem escollir categoria "gràfic" o "sistemes operatius" que no tenen cap programa. En IOS és particularment dur ja que moltes categories són buides. Si es escollim "Windows Phone" el problema és brutal.

Expectativa: que un cop selecciones un sistema operatiu (i més quan #190 estigui implementat) només es mostrin les categories amb contingut

Es podria també implementar aquest comportament pel selector "categoria", que al seleccionar una categoria deixés només les categories que tenen contingut per aquesta plataforma.

**Comment by xavivars** [comment]
El problema que té implementar això és que el cost computacional creix molt. Com bé dius, per a ser consistents, s'hauria de tindre en compte la combinació de categoria, plataforma i cerca de text: donat un estat de la cerca (amb una categoria X, una plataforma Y i un text Z) només s'haurien de mostrar:
* Categories que tinguen programes amb la plataforma Y i la cerca Z
* Plataformes que tinguen programes amb la categoria X i la cerca Z

Puc provar d'implementar-ho i podem provar, en test, com de bé/mal respon.
