### ISSUE TITLE
Formulari de programes nou: errors i limitacions

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#195]
A: https://www.softcatala.org/programes/ podem accedir al formulari de programes nous.

- Camp "versió" a " Dades de la baixada" hauria de ser opcional, així ho és quan edites la fitxa amb WP. A més per estalviar-nos feina d'actualització no definim la versió de la baixada, especialment en aplicacions mòbils.

- Al camp arquitectura a " Dades de la baixada" caldria afegir l'arquitectura N/A que és la que més usem per mòbils.

- Quan definim la captura de pantalla en català aquesta després no apareix en la fitxa. Simplement no funciona. Caldria comprovar si la pujada del logo funciona.

**Comment by xavivars** [comment]
Fixed: https://github.com/Softcatala/wp-softcatala/commit/e602bf303b0200bf73bf8fc30047e0f74f2d3c18
