### ISSUE TITLE
Rebost: WordPress vs MediaWiki

### ISSUE THREAD

**Issue by xavivars** [Softcatala/web-2015#2]
A l'hora d'implementar la nova web, hem de decidir què fem amb el Rebost. Hi ha diverses opcions:
* Tot a **MediaWiki**
 * Tal i com està actualment, tota la gestió del Rebost recau en MediaWiki
* Tot a **WordPress**
 * La idea seria moure tant el front-end com el back-end al WordPress
* Híbrid: Una altra opció seria utilitzar MediaWiki com a *font* del contingut, encarregant-se de la part de back-end, i utilitzar el WordPress com a front-end. Podria ser tant en "viu", com utilitzant algun procés periòdic per a, utilitzant les API webs que proporcionen tant MW com WP, sincronitzar els continguts.
 * API de WordPress (mitjançant plugin): **[WP-API](https://wordpress.org/plugins/json-rest-api/)**
 * [API de MediaWiki](https://en.wikipedia.org/w/api.php)

**Comment by PauGNU** [comment]
+1 per migració i ús a wordpress

El dl. 22 de juny de 2015 13.20 Xavi Ivars <notifications@github.com> va
escriure:

**Comment by jordimas** [comment]
Hola!

Voleu incloure Aparells (https://www.softcatala.org/wiki/Aparells) com a part d'aquesta conversa també? Ho dic perquè els requeriments són semblants.

Jo començaria per documentar els requeriments per poder parlar de la millor plataforma per satisfer-los.

Per exemple:

* Que qualsevol usuari pugui afegir un programa fàcilment
* Que qualsevol usuari pugui suggerir esmenes fàcilment
* Que un programa pugui pertànyer a múltiples plataformes
* Poder fer llistats per categories / plataformes 
* Poder canviar el nom a un programa i establir una redirecció 301 (això és important ja que moltes fitxers tenen molts enllaços)
* Que els programes es poguessin votar
* Que poguessin automatitzar les noves versions (com fem amb Firerfox amb els bots del Toni)
* Que la meta informació s'exportés com a meta-dades pels cercadors (nou)
* Que es pugessin fer reviews als programes es poguessin moderar. Penseu es com es mostra al Google Play per exemple (nou)
* Que poguéssim incloure el nombre de baixades a la fitxa (nou)

Un cop tinguem clars els requeriments parlaria de les dues solucions plantejades per implementar aquestes requeriments i els avantatges, inconvenients, i cost . Per exemple, en concret per la implementació amb WordPress quins plugins caldria usar, si caldrà escriure plugins nous o millorar els existents,  etc. 

Aquesta conversa també l'haurem de tenir alhora d'implementar-ho ja que caldrà ser molt transparent amb les solucions que escollim. Penseu també en els criteris de la solucions que vaig comentar fa temps i que cal debatre encara (https://www.softcatala.org/wiki/Usuari:Jmas/Requisits_t%C3%A8cnics)

**Comment by xavivars** [comment]
@jordimas, això era realment el que volia que discutirem, més enllà de "votar" per una opció o l'altra.

Aquest migdia he començat a obrir aquests *issues* per a poder dividir les preguntes que tenim, per anar discutint-les i arribant a conclusions, idealment abans de que arribe el moment d'implementar-les. Però de fet ni tan sols havia enviat encara cap missatge a la llista de correu (i no recordava que uns quants automàticament rebíeu notificacions).

La idea és que anem detallant cadascun dels requeriments (n'hi ha algun dels que defineixes que no estic 100% convençuts que els necessitem, i d'altres que s'haurien de definir més).

Però com ja he dit, només he obert dos *issues* per a preguntar-vos en general com veieu utilitzar aquesta plataforma per decidir eixe tipus de coses (independentment de que, una vegada presa una decissió, ho documentem tot a una pàgina wiki).

**Comment by jordimas** [comment]
Sí, he rebut la notificació i pensava que es volia encetar el debat :)

Al meu parer:

* En la meva experiència el sistema de Github  d'issues no és massa efficent per discutir requeriments.   Ho vam intentar amb les eines de memòries i els gallecs i va ser força dificultós. He tingut millor experiència amb la Wiki i llista de correu.  

* Jo crec que primer hauríem de parlar dels requeriments i les solucions abans de parlar de plataformes. Personalment no tinc massa apego a cap plataforma.

Dit això WordPress em sembla una opció ha tenir en compte ja que els que coneixeu la plataforma i el problema heu dit que esteu a favor de considerar-la.

Jordi,

**Comment by PauGNU** [comment]
Tecnologia:
1. WordPress per a totes les seccions generals del web
2. Discourse per als fòrums
3. MediaWiki per a tot el contingut relacionat amb les trobades, propostes que treballem normalment, esborranys de notícies i propostes o discussions.


- Tant el WordPress com el MediaWiki poden satisfer els requisits d'aquest model de col·laboració i tots dos tenen els seus avantatges i inconvenients. És important remarcar ambdues tecnologies poden satisfer aquests requisits sense grans complicacions.
- Es tria WordPress perquè:

    Com a eina de col·laboració té un editor molt més amigable que el wikitext de mediawiki. Això facilitarà la tasca als possibles col·laboradors.
    Un punt important és que Xavi (qui coneix WordPress) podrà dedicar més temps al seguiment del projecte del que ara mateix pot dedicar el Toni (qui coneix MediaWiki).

- Caldrà fer tota una sèrie de migracions de contingut, sobretot la relativa als projectes i rebost.
- MediaWiki es continuarà fent servir com a eina de col·laboració de contingut relatiu a trobades, propostes de notícies, creació de contingut propi dels membres de SC.
- Discourse es tria perquè és un sistema de fòrums molt complet amb una mode de funcionament molt intuïtiu i modern en comparació amb phpbb.

**Comment by PauGNU** [comment]
Hi Softcatala/web-2015,

I&#39;d like to include you in my network to share updates and stay in touch.

- Pau

Confirm that you know Pau: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=xak5UPKq&invitationId=6203268122292609024&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eivfj6co2%7Elz








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ivfj6co2-lz&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHQ3A4TpJWwxgAAAVhZvpv4drlY0w89yEGfUb-x8Aw0VNbLY6fsOW3E8lQ0HHm-QL1Z0mw_6b_a_kqmldCK1GGewMN49T83PZXjM_WZpLTD_FMIB7zLYcx6hwCLqGm1S4u6kJAvu2XQ6wDRdFGqv2lgxXn_r1-Q977V-7qvRh8crhuseKK85b2Vd7GdyXyL9P9a&eid=0-ivfj6co2-lz


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ivfj6co2-lz&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by PauGNU** [comment]
Pau Iranzo would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=xak5UPKq&invitationId=6203268122292609024&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-gahi0b%7Eivm5t8x0%7Enj

View Pau Iranzo&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=xak5UPKq&invitationId=6203268122292609024&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-gahi0b%7Eivm5t8x0%7Enj





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=gahi0b-ivm5t8x0-nj&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=gahi0b-ivm5t8x0-nj&loid=AQFkCG_yoGo9YQAAAVhycjfgbgol57v7lE9k1rH3Mf3iKJC0xTjocC9asH_AcG_nCr4GocPl2Hn5Ol6Gn76BIIVkxVYEMkloZsF2diWIq5PKaYdvZvzXe_MbzeF9mIyEx8FixQhx3e1OQWBADyn2svf4ReOA8Lm9NQAgY4K_mP_LGwzAh6MD5PUooQZTTz_f-Pyy

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=gahi0b-ivm5t8x0-nj&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by PauGNU** [comment]
Hi ,

Pau Iranzo would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=xak5UPKq&invitationId=6203268122292609024&trk=eml-second_guest_reminder_01-hero-120-accept_text&trkEmail=eml-second_guest_reminder_01-hero-120-accept_text-null-gahi0b%7Eiw1valnl%7Ex8

View Pau Iranzo&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=xak5UPKq&invitationId=6203268122292609024&trk=eml-second_guest_reminder_01-hero-3-profile_text&trkEmail=eml-second_guest_reminder_01-hero-3-profile_text-null-gahi0b%7Eiw1valnl%7Ex8





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=gahi0b-iw1valnl-x8&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=122&m=unsub&ts=HTML&eid=gahi0b-iw1valnl-x8&loid=AQF-Nt51BgS6JAAAAVirfCAGq65NAwYF_60fIuoese3fjhXynwibhpkbOYo4R1Rjf0YuvHcpBJKXu0QCAxPHFf9jBoWCoYQZ9Fvjj8ejQ8uaC-QRIEEbk255F4pSQdojJKzv2Hz6X28gQQqIDPA194AuToWKqp7UPg5F5rwqlHkOfKAz1v69tYejWtAyY-I5aMsxfyd1cYuHOVpRDqc5D4HJ-hHeDA

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=gahi0b-iw1valnl-x8&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
