### ISSUE TITLE
Pàgina en en-que-treballem

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#200]
La pàgina https://www.softcatala.org/en-que-treballem/ està buida

Estaria molt bé que fos un llistat de les 5 àrees que treballem així ho podríem enllaçar des de les comunicacions en xarxes socials com a punt d'entrada. Ara mateix només podem enllaçar a quelcom com https://www.softcatala.org/en-que-treballem/traduccio-de-programari/ que dóna una visió parcial del que fem

**Comment by xavivars** [comment]
@jordimas la pàgina ja té els enllaços, però no m'agrada gens... Ens cal algú que faça la part de disseny.
