### ISSUE TITLE
Eliminar el resize del textarea a la pàgina del corrector

### ISSUE THREAD

**Issue by mgm793** [Softcatala/web-2015#203]
Per que el textarea no faci coses rares quan l'usuari canvii la mida és millor treure el resize.

**Comment by xavivars** [comment]
Hola @mgm793, a quin textarea et refereixes?

**Comment by mgm793** [comment]
Aquest
![capture](https://user-images.githubusercontent.com/11296854/41407354-7305f2de-6fcf-11e8-9569-9b79c75e15eb.PNG)

**Comment by jaumeortola** [comment]
Aquesta petició s'ha atès. Però hem rebut peticions d'usuaris en sentit contrari que reclamen que es pugui canviar la dimensió sobretot per a treballar amb texts llargs. 

En algun lloc crec que vaig llegir que els problemes apareixien en mòbils. Podria eliminar-se el resize per a pantalles de mòbils i mantenir-se per a pantalla d'escriptori.

**Comment by jaumeortola** [comment]
Tenim més reclamacions sobre aquesta qüestió. 
La solució que jo propose és:
* Eliminar el resize per a la versió mòbil. 
* Mantenir el resize per a la versió d'escriptori.
