### ISSUE TITLE
L'avís de les galetes, centrat

### ISSUE THREAD

**Issue by Ecron** [Softcatala/web-2015#207]
Podiem fer que l'avís de les galetes no estiguera tot centrat (`text-align: center`), sinó millor repartit en la finestra.

Una mostra:

![captura de pantalla a 2018-12-16 14-59-57](https://user-images.githubusercontent.com/488803/50054552-51e66100-0143-11e9-9370-01610c3920f7.png)

**Comment by xavivars** [comment]
En principi, ho deixem tal i com està.
