### ISSUE TITLE
Avís del widget de Twitter respecte a les timelines embedded

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#211]
Quan navegues a pàgines com https://www.softcatala.org/projectes/gnome/, a la consola del navegador diu:

You may have been affected by an update to settings in embedded timelines. See https://twittercommunity.com/t/deprecating-widget-settings/102295. 

`<a class="twitter-timeline" href="https://twitter.com/softcatala" data-widget-id="349615365229277184" data-chrome="noscrollbar" data-tweet-limit="3" lang="ca" data-twitter-extracted-i1563804091791940125="true">Tuits de @softcatala.org</a>`

Usant https://publish.twitter.com/ el nou codi que suggereix és:

`<a class="twitter-timeline" data-lang="ca" href="https://twitter.com/softcatala?ref_src=twsrc%5Etfw">Tweets de @softcatala.org</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`

**Comment by xavivars** [comment]
Arreglat!
