### ISSUE TITLE
Format hora en català

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#213]
Veure:

Cal:
* Repasar el CSS/HTML de la pàgina. Ara mateix no es responsibe. Segurament cal canviar la taula per un CSS.
* Ara mateix els Javascript estan inclosos al final de la pàgina. Cal pensar si ens està bé o caldria tenir possar-los al head (penso que cal una extensió)
* Ara mateix el JS està publicat a https://www.softcatala.org/recursos/hora/. Cal pensar com i fer el deployment dels JS. No hauríen d'estar a recursos

**Comment by xavivars** [comment]
Puc encarregar-me de les dues primeres coses.

Respecte a la tercera, en el cas de, per exemple, els JS de la resta de serveis (traductor, corrector, etc) formen part del deployment del tema de WordPress. 

https://github.com/Softcatala/wp-softcatala/tree/master/static/js

Crec que és una bona opció, però depén molt de la freqüència d'actualització que vulguem tindre per a aquest JS. No perquè no es puguen fer deployments freqüents, sinó perquè habitualment no ens cal fer-ne, i fer-ho només per a este JS no paga massa la pena. Si et sembla bé, ho matenim a recursos fins que siga més estable i després ho movem amb la resta?

Crec que sóc partidari de

**Comment by jaumeortola** [comment]
Les solucions que apliqueu ací s'haurien d'aplicar igual a https://github.com/Softcatala/separador-sillabes.

**Comment by jordimas** [comment]
Entenc que això ja està fet. Si no és així, re-obriu el tiquet.
