### ISSUE TITLE
Firefox en valencià

### ISSUE THREAD

**Issue by jmontane** [Softcatala/web-2015#216]
Manca:

- Integrar les actualitzacions automàtiques de versions en la fitxa del Firefox en valencià https://www.softcatala.org/programes/firefox-en-catala-valencia , com ho tenim en la fitxa clàssica.

**Comment by xavivars** [comment]
Fixed by https://github.com/Softcatala/web-2015/commit/bf5354fbd337246253556499cf52ff7cd9daf373
