### ISSUE TITLE
Integració conjugador de webs

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#217]
Aquí el dipòsit del nou servei de conjugador de verbs:

https://github.com/Softcatala/conjugador

L'API actual és molt senzill:
* Search: http://localhost:8000/search/cantar
* Index: http://localhost:8000/index/a

A producció ho tenim desplegat també: https://www.softcatala.org/api/conjugador/search/cantar

La interfície d'usuari hauria de ser semblant (l'API també ho és) al diccionari multilingüe:
* Una pàgina principal de cerca https://www.softcatala.org/diccionari-multilingue/ on introdueixes un verb i et mostra el resultat
* Un índex per parula que llista tots els verbs per inicial. Això és molt important perquè els usuaris puguin navegar pel contingut però també perquè Google ho pugui trobar i indexar

**Comment by xavivars** [comment]
L'API és molt semblant al diccionari multilingüe, es pot reaprofitar molta cosa.

**Comment by mpiulats** [comment]
Publicat!
