### ISSUE TITLE
Actualització de versions del Tor de forma automàtica

### ISSUE THREAD

**Issue by jmontane** [Softcatala/web-2015#219]
Doncs això, estaria bé actualitzar els enllaços de baixada i número de versió de la fitxa del navegador Tor [1].

Fa tota la fila que el navegador Tor consulta si hi ha una versió nova disponible usant el json que hi ha en aquest URL [2].

[1] https://www.softcatala.org/programes/navegador-tor/
[2] https://aus1.torproject.org/torbrowser/update_3/release/downloads.json

**Comment by xavivars** [comment]
https://api.softcatala.org/rebost-releases/v1/tor
