### ISSUE TITLE
Canonicals a les pàgines d'índex

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#223]
Les pàgines d'índex de lletres com ara (que són les que usem):

https://www.softcatala.org/conjugador-de-verbs/lletra/W/

Al cannonical diem:

`<link rel="canonical" href="/conjugador-de-verbs/lletra/w/" />`

Caldria que les URLs que usem i el canonical coincideixin exactament.

Això podria ser una oportunitat per deixar el canonical com està i possar en minúscula els enllaços a la web, és a dir, en comptes de fer:

https://www.softcatala.org/conjugador-de-verbs/lletra/W/

fer

https://www.softcatala.org/conjugador-de-verbs/lletra/w/

**Comment by xavivars** [comment]
jo de fet posaria l'URL en minúscula... 😅

**Comment by jordimas** [comment]
Actualitzo el primer comentari perquè reflectixi el requeriment

**Comment by mpiulats** [comment]
Està resolt.
