### ISSUE TITLE
Conjugador de webs: Google mostra el 404 com la pàgina més visitada

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#227]
Conjugador de webs: Google mostra el 404 com la pàgina més visitada

![conjugador](https://user-images.githubusercontent.com/309265/82139732-56c4ae00-982a-11ea-9d08-54938369702f.png)

Solució desitjada: que les estadístiques reflecteixi el que veu l'usuari

**Comment by mpiulats** [comment]
Ara ja no s'agrupen els 404 en un error i podem veure el llistat d'errors.
