### ISSUE TITLE
Text "Formes verbals" al corrector

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#228]
El text "formes verbals" al https://www.softcatala.org/corrector/ no és correcte ja que impacte a més coses que les formes verbals. Amb en @jaumeortola vam dir de canviar-ho per "Varietat"

**Comment by jaumeortola** [comment]
No estic segur que "varietat" sigui la millor solució o la que (estèticament) m'agradi més. És una qüestió a la qual hem donat moltes voltes (@jmontane). L'últim canvi va ser aquest: https://github.com/Softcatala/wp-softcatala/commit/19ee091c19996018aa06477e238a4b2a52b285bb
Les diferències que hi ha són aquestes:
- Formes verbals.
- En valencià, s'utilitza un diccionari que conté tot el DNV.
- En valencià, hi ha més opcions (este/aquest, café/cafè, existix/existeix...) que l'usuari pot triar.
- Les variants seua/seva. Podrien passar a opcions generals, perquè algú a vegades ho ha demanat com a opció del nord-occidental. Però si es fa aquest pas, la "lògica" de tot queda molt estranya perquè encara hauria d'haver-hi unes opcions per defecte quan es canvia de varietat. 

Podríem posar:
- varietat central / valenciana / balear
- formes centrals / valencianes / balears
- altres?

**Comment by xavivars** [comment]
sé que molta gent li atribueix connotacions negatives però i dialecte?

**Comment by xavivars** [comment]
Volem fer alguna cosa amb este ticket?

**Comment by jordimas** [comment]
Jo vaig proposar "varietat" però sembla que "formes" seria millor. Ho canviem a formes llavors @jaumeortola que és una de les propostes?

**Comment by jordimas** [comment]
Hola @jaumeortola, això porta obert fa tres anys. Si ho no anem, a canviar-ho, també és cert que no s'ha queixat ningú, tancaré llavors el tiquet.
