### ISSUE TITLE
Afegir al corrector un botó per esborrar el text introduït

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#229]
Faig servir molt el corrector al mòbil i cada cop que vull corregir un altre text he d'esborrar l'actual a mà i és un conyàs. Això o recarregar la pàgina.

Suggereixo considerar incloure un botó X (com el que hi ha a la captura de sota a la part superior dreta) per esborrar el contingut del camp.

![Screenshot_20200606-151840](https://user-images.githubusercontent.com/309265/83945222-92d7a700-a809-11ea-9f52-1ce35dc53359.png)

**Comment by jaumeortola** [comment]
Ja existeix aquesta petició de fa temps: https://github.com/Softcatala/wp-softcatala/issues/212
