### ISSUE TITLE
Petites correccions i canvis al neural

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#234]
* Aproximament un 5% dels usuaris posen un text en català quan tenen seleccionada la traducció anglès -> català o en anglès quan tenen català -> anglès. Ara el servidor a la trucada /translate et retorna el camp source_language_wrong = True quan això succeïx. Per reproduir-ho, amb l'anglès -> català seleccionat pots demanar traduir "Hola amics de Palma"
Quan es retorna això si l'usuari té escollit el català -> anglès, caldria suggerir-li la direcció contraria i viceversa

* A la secció "Traducció de fitxers de text" cal llevar el text "Permet l'ús del text de manera anònima per a millorar el servei de traducció" ja que això no hem en el processament de fitxers.

* <del>A través de les xarxes socials ens han fet arribar que el text "Voleu provar la versió preliminar del traductor neuronal automàtic anglès-català que hem desenvolupat?" no és prou clar. </del>

**Comment by jaumeortola** [comment]
>  A través de les xarxes socials ens han fet arribar que el text "Voleu provar la versió preliminar del traductor neuronal automàtic anglès-català que hem desenvolupat?" no és prou clar. Caldria XXXXX

Fet aquí: https://github.com/Softcatala/wp-softcatala/commit/5940876e48ff792d220ddd3cd06dd3a0a7649a99
