### ISSUE TITLE
Scripts per a mantenir actualitzades les fitxes d'alguns programes

### ISSUE THREAD

**Issue by jmontane** [Softcatala/web-2015#237]
Per a alguns programes tenim uns scripts que extrauen l'última versió i l'enllaç de baixada, similar a com ho fem amb el Firefox.

Potser seria bona idea moure'ls a algun lloc intern del WP

Programes:

- [x] LibreOffice ([script](https://gent.softcatala.org/jmontane/libo/check-version.sh), [resultat](https://gent.softcatala.org/jmontane/libo/latest_files.txt))
- [x] Extensió LanguageTool per al LibreOffice ([script](https://gent.softcatala.org/jmontane/check-version/languagetool/check-version.sh), [resultat](https://gent.softcatala.org/jmontane/check-version/languagetool/latest_files.txt))
- [x] Ubuntu ([script](https://gent.softcatala.org/jmontane/check-version/ubuntu/check-version.sh), [resultat](https://gent.softcatala.org/jmontane/check-version/ubuntu/latest_files.txt))
- [x] calibre ([script](https://gent.softcatala.org/jmontane/check-version/calibre/check-version.sh), [resultat](https://gent.softcatala.org/jmontane/check-version/calibre/latest_files.txt))
- [x] mozilla
- [x] digiKam (https://www.digikam.org/download/)
- [x] GCompris (https://gcompris.net/downloads-ca.html)
- [ ] OpenSUSE (https://get.opensuse.org/leap#download)
- [x] Kdenlive (https://www.softcatala.org/programes/kdenlive/)
- [x] Krita (https://www.softcatala.org/programes/krita/), però només la baixada per a l'OSX
- [x] Transmission (https://www.softcatala.org/programes/transmission/), però només les baixades per al Win 64 i 32, i l'OSX

**Comment by xavivars** [comment]
Per al calibre he seguit un enfocament distint, que permet no haver de fer parsing de l'HTML, però perdem saber fàcilment la mida dels progrmaes. De moment ho deixaré com està, però deixe ací els enllaços per si ens ho replantegem:
- https://download.calibre-ebook.com/
- http://code.calibre-ebook.com/latest

**Comment by txemaq** [comment]
Afegeixo uns candidats a actualitzar l'enllaç de baixada mitjançant script:

- digiKam (https://www.digikam.org/download/)
- GCompris (https://gcompris.net/downloads-ca.html)
- OpenSUSE (https://get.opensuse.org/leap#download)

**Comment by xavivars** [comment]
Gràcies!

Afegits al post inicial

**Comment by xavivars** [comment]
https://github.com/Softcatala/rebost-releases

**Comment by txemaq** [comment]
Afegeixo 3 candidats nous a actualitzar l'enllaç de baixada mitjançant script:

- Kdenlive (https://www.softcatala.org/programes/kdenlive/)
- Krita (https://www.softcatala.org/programes/krita/), però només la baixada per a l'OSX
- Transmission (https://www.softcatala.org/programes/transmission/), però només les baixades per al Win 64 i 32, i l'OSX

**Comment by xavivars** [comment]
No veig manera senzilla d'actualitzar OpenSuse i, a més, sembla que només trauen una versió nova cada any. No té massa sentit invertir molt de temps automatitzant-ho. La resta de programes ja estan automatitzats.
