### ISSUE TITLE
Incloure definicions al conjugador de verbs

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#238]
Canvis que cal fer:

**Mostrar definició**

El conjugador de verbs ara retorna:
* Una definició a mostrar (ara mateix el 50% dels casos) - camp  Veure: https://www.softcatala.org/api/conjugador/search/cantar ( (camp definition_url)
* Una URL a una definició Veure: https://www.softcatala.org/api/conjugador/search/abuanyar (camp definition_url)

**Mostra crèdits**
Sempre es retorna un camp "definition_credits" que hi ha que mostrar al final de la pàgina per donar crèdit i convidar a la participació

**URL de l'API**
Canviar la URL de l'API de https://www.softcatala.org/api/conjugador/search/cantar a https://api.softcatala.org/conjugador/v1/search/cantar

**Comment by xavivars** [comment]
El text dels crèdits no té sentit quan no hi ha cap definició. Segurament el missatge hauria de ser diferent si hi ha definició a mostrar o només enllaç.

**Comment by jordimas** [comment]
Ara mateix la lògica que hi ha és aquesta:

https://github.com/Softcatala/conjugador/blob/a2a4c29676d9f91ef9e1643c8177210d159b01d0/extractor/extract.py#L341

Possar el text a crèdits sempre va ser un suggeriment d'en @pereorga per fomentar la participació al diccionari upstream quan no hi ha un terme. És pot millorar la implementació,  però la idea em sembla bona.

**Comment by xavivars** [comment]
Si. Bàsicament, la meua proposta és canviar el text segons si hi ha o no definició (i és independent de la integració a la web)

**Comment by jordimas** [comment]
Per mi endavant. Jo no estaré davant d'un PC en els pròxims dies, llavors tira milles 👍

**Comment by mpiulats** [comment]
L'API ja està canviada doncs la podem configurar amb una opció del WordPress.

**Comment by xavivars** [comment]
Miquel, no sé què vols dir.... 

La meua proposata és que si l'API sempre torna el text de crèdits, que en torne un de diferent. I després al WordPress simplement mostra el que li diga l'API

**Comment by mpiulats** [comment]
Jo només em referia al canvi d'URL de l'API.

**Comment by xavivars** [comment]
Ja està a producció
