### ISSUE TITLE
Errades a corregir a les mètriques

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#239]
Errades a les mètriques:

1) Les mètriques alguns cops surten duplicades  Estic en un lloc amb molt mala connexió, crec que està relacionat en què la trucada al servidor ha fallat. Caldria revisar com es gestiona el buidatge de la capsa i com es comporta si la trucada dóna error. Hi ha alguna condició que no gestionem bé

![image](https://user-images.githubusercontent.com/309265/120620490-4eeba200-c45d-11eb-9709-4cd9a921e838.png)

2) El botó "Neteja"  hauria de netejar també les mètriques i no deixar les del text anterior que un cop premut "   Neteja" ja no es veu

**Comment by mpiulats** [comment]
Solucionat!
