### ISSUE TITLE
[General] Afegir tags Facebook a la capçalera

### ISSUE THREAD

**Issue by PauGNU** [Softcatala/web-2015#46]
Aquests tags s'han d'afegir a cada tecnologia (no són tags genèrics i per tant cada tecnologia tindrà el seu propi contingut:

        
        <meta property="og:title" content="xxxxxxxxxx" />
        <meta property="og:type" content="xxxxxxxxxx" />

        <meta property="og:url" content="xxxxxxxxxxxxx" />
        <meta property="og:image" content="xxxxxxxxxxxx" />
        <meta property="og:site_name" content="xxxxxxxxxxxxx" />
        <meta property="og:description" content="xxxxxxxxxxxx" />

**Comment by xavivars** [comment]
Per a WordPress, l'extensió Yoast SEO fa això i molt més 😊

**Comment by PauGNU** [comment]
Perfecte, farem servir l'extensió que calga per a cada tecnologia.

* [ ] WordPress - Yoast SEO
* [ ] Discourse
* [ ] MediaWiki
