### ISSUE TITLE
Problemes d'estils

### ISSUE THREAD

**Issue by xavivars** [Softcatala/web-2015#51]
- [x] Els enllaços al cos de la notícia no tenen els colors adeqüats. (Només dins del cos) haurien de ser roig (utilitzant les variables `@link-color` i `@link-color-hover`
- [ ] Ordenació al menú esquerra de la plantilla `menu-left`

Falten els estiils predeterminats del WordPress ([més informació](https://codex.wordpress.org/CSS))
- [x] Imatges
- [ ] Llegenda baix de les imatges

**Comment by PauGNU** [comment]
@xavivars , crec que tot això ja està resolt, no?

**Comment by xavivars** [comment]
Diria que si...
