### ISSUE TITLE
[Cache] Instal·lar full-page i object cache per al WordPress

### ISSUE THREAD

**Issue by xavivars** [Softcatala/web-2015#52]
Necessitem dos nivells de cache, full-page (a nivell de nginx) i object cache (per al WordPress).

Cadascun dels nivells ofereix diverses opcions

* Full page.
 * WP-Supercache
 * Varnish
 * Redis
* Object cache
 * Motor de cache: Memcache
 * Motor de cache: Redis
 * Plugin de Wordpress: [Redis Cache](https://wordpress.org/plugins/redis-cache/)

La part bona: easy-engine configura automàticament Redis per a que funcione tant per a la cache de pàgina completa com per a l'object cache, o siga que jo començaria provant això.

**Comment by PauGNU** [comment]
Hola,

Seguint els passos indicats en aquest [howto](https://www.digitalocean.com/community/tutorials/how-to-configure-redis-caching-to-speed-up-wordpress-on-ubuntu-14-04) i a la [pàgina de l'easyengine](https://rtcamp.com/blog/easyengine-3-3-full-page-redis-cache/), ja he instal·lat l'object cache i el full page cache a tots els entorns. Això ha requerit bàsicament:

1. Instal·lar els paquets de redis (teòricament això ho hauria de fer el redis, però ho he fet manualment jo abans a partir dels repos):
`apt-get install redis-server php5-redis`

2. Executar l'ordre update de l'easyengine:
`ee site update softcatala.org --wpredis`

3. Modificar l'wp-config.php a web-2015 per a dir-li al wordpress que faça servir Redis

4. Modificar el composer.json per a que baixe automàticament la darrera versió d'object-cache.php

Redis ja està actiu a web2015 i web2016. Es pot monitoritzar amb:
`redis-cli monitor`

**Comment by PauGNU** [comment]
Per a la nostra informació. El temps de càrrega amb l'object-cache i full-cache page actiu és d'uns 100ms, quan sense cap tipus de cache, estem en valors de 500-1000ms.

Bona millora :)

**Comment by xavivars** [comment]
:+1:

**Comment by xavivars** [comment]
Crec que he trobat el problema: ![image](https://cloud.githubusercontent.com/assets/134083/13547280/40ad15de-e29a-11e5-9ad8-4c1fa66d2892.png)

Potser l'extensió no està ben instal·lada?

**Comment by PauGNU** [comment]
En realitat, no cal instal·lar cap extensió. Si mires web2016, ho veuràs. Per a web2015, esborra totes les cookies, ja que sembla que hi ha alguna cookie de sessió que queda per ahí i que el full-page cache pren com suficient per no fer hit.

Jo acabe de fer la prova, i tot bé. Prova amb:

1. Esborra totes les cookies
2. Sense tancar l'inspector, vés a qualsevol pàgina. Fixa-t'hi que el temps de càrrega de la pàgina, degut a que probablement serà la primera vegada que es visita i que no està en cache, és un temps de càrrega com si no hi haguera cache. Veuràs que el paràmetre de cache posa 'bypass'.
3. Si actualitzes ara la pàgina, veuràs que carrega molt més ràpid i que el paràmetre de cache està a hit.

El problema de l'extensió és degut a que vaig estar provant diferents extensions, però al final no calia fer res més que posar l'object-cache.php i ja està. Aquestes extensions de redis no fan més que afegir el paràmetre de cache a la configuració i algunes gestionen el refresc de cache quan es fan canvis.

L'extensió que l'easyengine instal·la per defecte, nginx helper, sembla que ja fa això últim. A més, a la llarga haurem de fer canvis per veure en quins moments volem 'nosaltres' refrescar la cache.

Prova amb això que t'he dit.
