### ISSUE TITLE
[Entorns] Preparació entorn desenvolupament/test

### ISSUE THREAD

**Issue by PauGNU** [Softcatala/web-2015#6]
- [x] Entorn desenvolupament WordPress
- [ ] Entorn desenvolupament Discourse
- [ ] Entorn desenvolupament MediaWiki

**Comment by jordimas** [comment]
Hola Pau,

Alguns comentaris:

1) Podem documentar quina és la proposta tècnica pels entorns?

Per exemple,  si aquests sistemes compartiran màquines virtuals, si aniran en màquines virtuals independents, si compartiran base de dades, etc. Descriure com es vol implementar tècnicament perquè pugem parlar-lo abans que es faci.

2) M'agradaria definir quin és l'estratègia pels serveis com traductor, corrector, diccionari de sinònims, recursos, etc. Tots aquests sistemes haurien de tenir les seves versions de desenvolupament, quin ho tenen ja, on viuen, com es configuraran les adreces, etc.

3) M'agradaria també saber si estem considerant fer integració continua amb l'entorn de desenvolupament. Jo ho tinc fet per recursos per exemple. Com es planteja la migració de dev a prod, etc.

4) Crec que es fonamental que com a part d'aquesta tasca es crei una documentació descrigui exactament com funcionen aquests entorns i on són les coses.

Gràcies

Jordi,

**Comment by PauGNU** [comment]
Hola Jordi,

Al wiki intern de SC s'ha creat una tasca relacionada amb això:
https://intern.softcatala.org/wiki/Bug:Documentaci%C3%B3_web-2015_de_SC_726417

S'ha creat la pàgina següent:
https://intern.softcatala.org/wiki/Web2015

Aquesta pàgina es va actualitzant conforme es van configurant les màquines, així com tota la informació necessària sobre cada tecnologia, etc. Ara mateix està tot a una mateixa pàgina, però possiblement serà interessant anar dividint-ho en subpàgines conforme avancem.

Respecte als quatre punts que comentes:
1) La resposta anterior hauria de ser suficient?

2) Això que comentes està relacionat amb aquestes tasques:
https://github.com/Softcatala/web-2015/issues/8 » repositoris github
https://github.com/Softcatala/wp-softcatala/issues/19 » estructura de directoris
Totes aquestes seccions que comentes, que en definitiva requereixen una integració de WordPress amb un altre servei (per exemple, el traductor o les memòries), tindran una estratègia diferent segons la tecnologia. Per exemple, el traductor:
» Tindrà una pàgina específica del WordPress amb un template (com ja s'ha fet a Softvalencià)
» El servei del traductor (a no ser que Xavi diga el contrari), es matindrà com fins ara i per tant no es requerirà cap desenvolupament o manteniment extra (a no ser que es desitge canviar-ho). Però l'actualització d'aquest servei no forma part del projecte en sí mateix. Es pot posar com a tasca col·lateral.

3) Mirat la proposta del Xavi:
https://github.com/Softcatala/wp-softcatala/issues/19 » actualitzacions i desplegaments

4) Com he comentat a dalt, tot el que s'ha pogut documentar fins ara ja s'ha fet i s'anirà actualitzant.
https://intern.softcatala.org/wiki/Web2015

**Comment by jordimas** [comment]
Gràcies Pau

En el futur suggereixo afegir en els tickets els enllaços necessaris per entendre com es farà la tasca. No tothom ha pogut participar en totes les converses i seguir tots els fils en múltiples fòrums, i la documentació està distribuïda en varis llocs que fa difícil de trobar si no estàs seguint el projecte molt de prop.

Sobre el punt 1. No m'ha quedat quina estratègia esteu proposant: màquina virtual per servei o compartició de màquines i com quedarà distribuït. A dia d'avui tenim màquines virtuals que tenen agrupacions de serveis que no tenen cap sentit i no s'ha seguit cap estratègia d'agrupació coherent de serveis. Per això, ara que s'estan definit els entorns trobo important detallar en la Wiki clarament qui és el pla: quines màquines virtuals hi haurà, quins serveis hi viuran, i quins entorns donaran suport. 

Un cop estigui aquesta informació, puc inclús fer un diagrama amb el Dia que il·lustri on és cada cosa gràficament. A títol personal, segons l'estratègia que es plantegi he de pensar en migrar recursos o no a un nou lloc nou. 

També vam comentar:

1) De documentar molt clarament quins passos s'han seguit per instal·lar cada cosa. Que si algun dia s'ha de muntar una màquina de zero tenir documentat que cal fer. 

2) Estandaritzar els ID usuaris i grups entre màquines per facilitar-ne moure serveis, no sé si això s'està fent.

En resum, com que estem configurant els entorns assegurar-nos que no heretem les coses que sabem volíem millorar de com ho tenim fet ara.

Atentament,

Jordi

**Comment by PauGNU** [comment]
Hola @xaviivars

Escolta, podem preparar l'entorn de 'staging'. Aquest entorn serà bàsicament allò que estarà llest per testejar (serà en el futur el pas abans de producció).

L'entorn que tenim actualment el deixem com a development/integration, si et sembla bé.

Salut
