### ISSUE TITLE
L'auxiliar d'afegir programes no cerca bé programes existents

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#61]
A /programes/ quan vols donar d'alta un programa nou apareix un auxiliar.

Al segon pas que diu:

"Voleu incorporar un programa nou?
Comproveu si el programa ja existeix al rebost"

Si cerco Catalanitzador que existeix, no m'apareix la fitxa però si altres com Sigil on es menciona el Catalanizador. Penso que de fet ho troba però no ho mostra.

Suggereixo:

- El cercador hauria de retornar primer qualsevol resultat de la cerca que coincidís amb el títol.
- Caldria indicar que hi ha més resultats que no s'han inclòs en la llista.

**Comment by PauGNU** [comment]
Hola Jordi,

He fet els canvis al cercador: s'ordena per títol, es mostren 5 resultats, i es poden desplegar més resultats.

Ja està a web2015.
