### ISSUE TITLE
Errades a les fitxes de programes

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#74]
Agafem com exemple: http://web2016.softcatala.org/programes/firefox/

Molt poca gent sabrà que vol dir "MPL 2.0". Ni tampoc "Mozilla" sense cap context addicional. Per altre banda, no apareix el camp de l'autor de la traducció.

Canvis que proposo:
- Afegir les llegendes "Llicència", "Autor", i "Lloc web" com tenim ara perquè quedi clar a que es refereixen els textos que apareixen
- Afegir el camp del autor de la traducció (fora bo a més no perdre aquesta informació que actualment tenim)

**Comment by PauGNU** [comment]
Hola Jordi,

* S'han afegit les llegendes (ens mancaria un disseny millor). 
* S'ha afegit el camp de 'autor de la traducció' (és un camp 'pla')
* S'ha afegit el camp 'projecte relacionat', que en cas d'estar definit enllaça al projecte relacionat

Exemple a web2016:
http://web2016.softcatala.org/catalanitzador/

(no he emplenat el camp d'autor de la traducció)
