### ISSUE TITLE
Eliminar el concepte de archivar en el directori de programes

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#78]
Els programes antics o que no són útils els esborrem. Podem prescindir completament de l'opció arxivar. Això inclou:

- No ens cal en la fitxa d'edició poder si està arxivat o no
- En la cerca  "Mostra el programari arxivat" no

**Comment by xavivars** [comment]
Jo això ho discutiria amb l'Anna abans d'implementar-ho. Ho vam posar al pla de continguts.
