### ISSUE TITLE
[General] Inicialització repositori GitHub

### ISSUE THREAD

**Issue by PauGNU** [Softcatala/web-2015#8]
- [x] Repositori tema WordPress
- [ ] Repositori plugins WordPress
- [ ] Repositori tema discourse
- [ ] Repositori tema mediawiki
- [x] Repositori per a contingut estàtic, scripts...

**Comment by xavivars** [comment]
Probablement necessitarem multiples repositoris. Idealment, el tema de WordPress hauria d'anar en el seu propi repositori, i cada extensió que necessitem, també en un repositori propi

**Comment by PauGNU** [comment]
Podem fer simplement «sub-repositoris» sobre web-2015?
