### ISSUE TITLE
Wiki. Cal crear un automatisme per esborrar tot l'espai de noms de Rebost, PreRebost i Aparells a la Wiki ja que s'han migrat.

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#87]
Cal crear un automatisme per esborrar tot l'espai de noms de Rebost, PreRebost i Aparells a la Wiki ja que s'han migrat. Projectes caldrà fer-ho manualment

**Comment by PauGNU** [comment]
Hola,

Sembla que és molt fàcil eliminar tots aquests elements. Els article del wiki estan identificats per diferents namespaces:

define("NS_REBOST", 100);
define("NS_REBOST_TALK", 101);
define("NS_PREREBOST", 102);
define("NS_PREREBOST_TALK", 103);
define("NS_PRE", 104);
define("NS_PRE_TALK", 105);
define("NS_POSTREBOST", 106);
define("NS_POSTREBOST_TALK", 107);
define("NS_DISPOSITIU", 108);
define("NS_DISPOSITIU_TALK", 109);
define("NS_FABRICANT", 110);
define("NS_FABRICANT_TALK", 111);

Faré una extracció d'articles i faré servir un script d'esborrat del propi mediawiki per eliminar-ho.

**Comment by xavivars** [comment]
Podem saber si hi ha "subpagines"  en algun d'aquestos namespaces que vulguem conservar? 

A l'espai de noms de projectes, per exemple, n'hi ha moltes que haurem de migrar...

**Comment by jordimas** [comment]
Ei, projectes no està a la llista de namespaces a borrar amb aquest script, vaig comentar que ho faria a mà. 

Jordi

**Comment by PauGNU** [comment]
Hola,

- Respecte a les subpàgines, crec que no hem de tindre por si les eliminem. Sempre podem crear una còpia del wiki en (per exemple), intern. Així sempre podrem accedir a qualsevol article si volem recuperar-lo o comparar-lo.

- Respecte a projectes, ho mire! Ho faràs tu a mà? @jordimas

**Comment by PauGNU** [comment]
Hola,

Els projectes estan a dintre del namespace 'PRE', però juntament amb la resta de pàgines generals del wiki (Guia d'estil, Història de Softcatalà, etc, etc.). Possiblement serà millor eliminar-los a mà.

**Comment by PauGNU** [comment]
Hola,

He fet una còpia de la BD i després he executat l'script que ha eliminat totes les pàgines de tots els namespaces excepte 'PRE', que és on es troben les pàgines que no pertanyen ni a rebost ni a aparells.

Si voleu, podeu fer una ullada.

**Comment by jordimas** [comment]
@PauGNU ja eliminaré jo projectes a mà les pàgines que toquin i la resta

**Comment by PauGNU** [comment]
Si vols que els eliminem amb l'script, la cosa és senzilla, ja que puc fer una consulta per obtenir els ids dels articles i després executar l'script de manteniment.
https://intern.softcatala.org/wiki/Web2015/Wiki

**Comment by jordimas** [comment]
Caldria també esmenar qualsevol referència de pàgines internes a aquests articles. SI ho pots fer fantàstic.

**Comment by PauGNU** [comment]
D'acord. Miraré com fer-ho.
