### ISSUE TITLE
Categoria sistema operatiu i baixada al directori de programes: reduir duplicitat

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#91]
La informació de sistema operatiu està duplicada. Per un costat tenim les definicions de les baixades (on indiquem sistema operatiu) per cada fitxa (URL, plataforma, etc) i per altra la categoria a mà esquerra quan edites les fitxes. De cara a l'usuari, usem aquestes últimes per filtrar.

Eliminar la duplicitat d'informació, reduint manteniment i inconsistències. Ara per exemple tenia una fitxa que l'he afegit la baixada de Windows però no em sortia al filtrar per sistema fins que l'he afegit la categoria també. 

Possible solució: Podem mirar de resoldre això mirant de fer una "actualització automàtica" de les categories de la fitxa en base a les baixades, de manera que al guardar la fitxa es miraren les baixades configurades i es posaren les categories adients. Però no posem llevar la categoria com a tal o els filtres seran molt lents.

**Comment by PauGNU** [comment]
Hola,

Efectivament, crearem un 'hook' per actualitzar automàticament els sistemes operatius d'un programa depenent dels sistemes operatius de les seues baixades.

**Comment by xavivars** [comment]
Ara mateix, la categoria s'assigna automàticament a partir de les baixades. Podem tancar aquest ticket ja.
