### ISSUE TITLE
/projectes mostra elements que no són projectes

### ISSUE THREAD

**Issue by jordimas** [Softcatala/web-2015#94]
Degut a com hem estructurat el lloc web /projectes/ mostra com a projectes que no són projectes com ara:

/projectes/traduccio-i-correccio/
/projectes/coordinacio-desdeveniments/
etc

Algunes opcions:
- Creem una opció per poder-los amagar
- Els estructurem com part de col·laborar a Softcatalà (el que són)

**Comment by xavivars** [comment]
* Traducció i correcció: eixe projecte l'hem d'esborrar.
* Coordinació d'esdeveniments: és de fet, de la manera en que vam estructurar la web, un "projecte" on la gent pot col·laborar. Bàsicament, quan discutíem de com organitzar el contingut, vam dir que la manera de col·laborar a Softcatalà es vehiculava a través de projectes. El que estic d'acord amb tu és que no té cap sentit mostrar-lo a la llista de "projectes", sinó que vinga enllaçat per a la gent que ve de col·laborar a través d'un perfil.
